# Generated by Django 5.0.2 on 2024-02-12 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
                ('type_of_contact', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('filepath', models.CharField(blank=True, max_length=200)),
                ('datetime', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('browser_specs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('seniority', models.CharField(choices=[('Board', 'Board'), ('Executive', 'Executive'), ('Manager', 'Manager'), ('Senior', 'Senior'), ('Junior', 'Junior'), ('Intern', 'Intern'), ('Staff', 'Staff'), ('Volunteer', 'Volunteer'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Anonymous', max_length=200)),
                ('authorisation', models.CharField(choices=[('Full', 'Full'), ('Limited', 'Limited'), ('None', 'None')], max_length=200, null=True)),
                ('influence', models.CharField(choices=[('Total', 'Total'), ('Max', 'Max'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Min', 'Min'), ('None', 'None')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('blurb', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('x_marketing', models.TextField(blank=True)),
                ('editor', models.CharField(default='Stuart McL', max_length=200)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='bookscot_site.directory')),
            ],
            options={
                'db_table': 'bookscot_site_directory',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(default='Article', max_length=200)),
                ('section', models.CharField(default='Main', max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('x_marketing', models.TextField(blank=True)),
                ('author', models.CharField(default='Sue B', max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bookscot_site.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('interests', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='bookscot_site.role')),
            ],
        ),
    ]
